[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
og_testnet = "https://evmrpc-testnet.0g.ai"

[etherscan]
og_testnet = { key = "", url = "https://chainscan-newton.0g.ai/api" }
